// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlcgen

import (
	"context"
	"time"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*) FROM users WHERE is_admin = TRUE AND active = TRUE
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminGroupMemberships = `-- name: CountAdminGroupMemberships :one
SELECT COUNT(*)
FROM user_groups ug
JOIN groups g ON g.id = ug.group_id
WHERE ug.user_id = $1 AND g.grants_admin = TRUE
`

func (q *Queries) CountAdminGroupMemberships(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminGroupMemberships, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccessTokensByUser = `-- name: DeleteAccessTokensByUser :exec
DELETE FROM access_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAccessTokensByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccessTokensByUser, userID)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const deleteRefreshTokensByUser = `-- name: DeleteRefreshTokensByUser :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByUser, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, created_at, source, ldap_source_id, grants_admin FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Source,
		&i.LdapSourceID,
		&i.GrantsAdmin,
	)
	return i, err
}

const getUserPhoto = `-- name: GetUserPhoto :one
SELECT photo, photo_mime FROM users WHERE id = $1
`

type GetUserPhotoRow struct {
	Photo     []byte
	PhotoMime *string
}

func (q *Queries) GetUserPhoto(ctx context.Context, id string) (GetUserPhotoRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPhoto, id)
	var i GetUserPhotoRow
	err := row.Scan(&i.Photo, &i.PhotoMime)
	return i, err
}

const listAdminGroupMemberIDs = `-- name: ListAdminGroupMemberIDs :many
SELECT DISTINCT ug.user_id
FROM user_groups ug
JOIN groups g ON g.id = ug.group_id
WHERE g.grants_admin = TRUE
`

func (q *Queries) ListAdminGroupMemberIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAdminGroupMemberIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT u.id, u.username, u.email, u.name, u.password_hash, u.source, u.is_admin, u.active, u.created_at, u.updated_at, u.ldap_source_id, u.ldap_dn, u.photo, u.photo_mime
FROM users u
JOIN user_groups ug ON ug.user_id = u.id
WHERE ug.group_id = $1
ORDER BY u.username
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Source,
			&i.IsAdmin,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LdapSourceID,
			&i.LdapDn,
			&i.Photo,
			&i.PhotoMime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsWithCounts = `-- name: ListGroupsWithCounts :many
SELECT g.id, g.name, g.created_at, g.source, g.ldap_source_id, g.grants_admin, COUNT(ug.user_id) AS member_count
FROM groups g
LEFT JOIN user_groups ug ON ug.group_id = g.id
GROUP BY g.id
ORDER BY g.name
`

type ListGroupsWithCountsRow struct {
	ID           string
	Name         string
	CreatedAt    time.Time
	Source       string
	LdapSourceID *string
	GrantsAdmin  bool
	MemberCount  int64
}

func (q *Queries) ListGroupsWithCounts(ctx context.Context) ([]ListGroupsWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsWithCountsRow
	for rows.Next() {
		var i ListGroupsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Source,
			&i.LdapSourceID,
			&i.GrantsAdmin,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAdminGroups = `-- name: ListUserAdminGroups :many
SELECT g.id, g.name, g.created_at, g.source, g.ldap_source_id, g.grants_admin
FROM groups g
JOIN user_groups ug ON ug.group_id = g.id
WHERE ug.user_id = $1 AND g.grants_admin = TRUE
ORDER BY g.name
`

func (q *Queries) ListUserAdminGroups(ctx context.Context, userID string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listUserAdminGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Source,
			&i.LdapSourceID,
			&i.GrantsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, name, password_hash, source, is_admin, active, created_at, updated_at, ldap_source_id, ldap_dn, photo, photo_mime FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Source,
			&i.IsAdmin,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LdapSourceID,
			&i.LdapDn,
			&i.Photo,
			&i.PhotoMime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserGroup = `-- name: RemoveUserGroup :exec
DELETE FROM user_groups WHERE user_id = $1 AND group_id = $2
`

type RemoveUserGroupParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) RemoveUserGroup(ctx context.Context, arg RemoveUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserGroup, arg.UserID, arg.GroupID)
	return err
}

const renameGroup = `-- name: RenameGroup :exec
UPDATE groups SET name = $1 WHERE id = $2
`

type RenameGroupParams struct {
	Name string
	ID   string
}

func (q *Queries) RenameGroup(ctx context.Context, arg RenameGroupParams) error {
	_, err := q.db.ExecContext(ctx, renameGroup, arg.Name, arg.ID)
	return err
}

const updateGroupGrantsAdmin = `-- name: UpdateGroupGrantsAdmin :exec
UPDATE groups SET grants_admin = $1 WHERE id = $2
`

type UpdateGroupGrantsAdminParams struct {
	GrantsAdmin bool
	ID          string
}

func (q *Queries) UpdateGroupGrantsAdmin(ctx context.Context, arg UpdateGroupGrantsAdminParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupGrantsAdmin, arg.GrantsAdmin, arg.ID)
	return err
}

const updateUserFlags = `-- name: UpdateUserFlags :exec
UPDATE users SET is_admin = $1, active = $2, updated_at = $3 WHERE id = $4
`

type UpdateUserFlagsParams struct {
	IsAdmin   bool
	Active    bool
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateUserFlags(ctx context.Context, arg UpdateUserFlagsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserFlags,
		arg.IsAdmin,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserIdentity = `-- name: UpdateUserIdentity :exec
UPDATE users SET name = $1, email = $2, updated_at = $3 WHERE id = $4
`

type UpdateUserIdentityParams struct {
	Name      string
	Email     string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateUserIdentity(ctx context.Context, arg UpdateUserIdentityParams) error {
	_, err := q.db.ExecContext(ctx, updateUserIdentity,
		arg.Name,
		arg.Email,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserPhoto = `-- name: UpdateUserPhoto :exec
UPDATE users SET photo = $1, photo_mime = $2, updated_at = $3 WHERE id = $4
`

type UpdateUserPhotoParams struct {
	Photo     []byte
	PhotoMime *string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateUserPhoto(ctx context.Context, arg UpdateUserPhotoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPhoto,
		arg.Photo,
		arg.PhotoMime,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
