// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlcgen

import (
	"context"
	"time"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*) FROM users WHERE is_admin = TRUE AND active = TRUE
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE active = TRUE
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminGroupMemberships = `-- name: CountAdminGroupMemberships :one
SELECT COUNT(*)
FROM user_groups ug
JOIN groups g ON g.id = ug.group_id
WHERE ug.user_id = $1 AND g.grants_admin = TRUE
`

func (q *Queries) CountAdminGroupMemberships(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminGroupMemberships, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApplications = `-- name: CountApplications :one
SELECT COUNT(*) FROM applications
`

func (q *Queries) CountApplications(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApplications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT COUNT(*) FROM user_groups WHERE group_id = $1
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroups = `-- name: CountGroups :one
SELECT COUNT(*) FROM groups
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupsSearch = `-- name: CountGroupsSearch :one
SELECT COUNT(*) FROM groups
WHERE lower(name) LIKE CAST($1 AS TEXT) ESCAPE '\'
  AND (CAST($2 AS TEXT) = '' OR source = CAST($2 AS TEXT))
`

type CountGroupsSearchParams struct {
	Pattern string
	Source  string
}

// Same pattern convention as the users search; an empty source means any.
func (q *Queries) CountGroupsSearch(ctx context.Context, arg CountGroupsSearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupsSearch, arg.Pattern, arg.Source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersSearch = `-- name: CountUsersSearch :one
SELECT COUNT(*) FROM users
WHERE (lower(username) LIKE CAST($1 AS TEXT) ESCAPE '\'
    OR lower(email) LIKE CAST($1 AS TEXT) ESCAPE '\'
    OR lower(name) LIKE CAST($1 AS TEXT) ESCAPE '\')
  AND (CAST($2 AS TEXT) = '' OR source = CAST($2 AS TEXT))
  AND (CAST($3 AS TEXT) = ''
    OR (CAST($3 AS TEXT) = 'active' AND active)
    OR (CAST($3 AS TEXT) = 'inactive' AND NOT active))
  AND (NOT CAST($4 AS BOOLEAN) OR is_admin
    OR id IN (SELECT ug.user_id FROM user_groups ug JOIN groups g ON g.id = ug.group_id WHERE g.grants_admin))
`

type CountUsersSearchParams struct {
	Pattern    string
	Source     string
	Status     string
	AdminsOnly bool
}

// The pattern is lowercased and wildcard-escaped by the caller ('%' for
// no filter). lower() keeps the match case-insensitive on both engines.
// An empty source / status means "any"; admins_only also counts members of
// an administrator-granting group.
func (q *Queries) CountUsersSearch(ctx context.Context, arg CountUsersSearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersSearch,
		arg.Pattern,
		arg.Source,
		arg.Status,
		arg.AdminsOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccessTokensByUser = `-- name: DeleteAccessTokensByUser :exec
DELETE FROM access_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAccessTokensByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccessTokensByUser, userID)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const deleteRefreshTokensByUser = `-- name: DeleteRefreshTokensByUser :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByUser, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, created_at, source, ldap_source_id, grants_admin, upstream_source_id FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Source,
		&i.LdapSourceID,
		&i.GrantsAdmin,
		&i.UpstreamSourceID,
	)
	return i, err
}

const getUserPhoto = `-- name: GetUserPhoto :one
SELECT photo, photo_mime FROM users WHERE id = $1
`

type GetUserPhotoRow struct {
	Photo     []byte
	PhotoMime *string
}

func (q *Queries) GetUserPhoto(ctx context.Context, id string) (GetUserPhotoRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPhoto, id)
	var i GetUserPhotoRow
	err := row.Scan(&i.Photo, &i.PhotoMime)
	return i, err
}

const listAdminGroupMemberIDs = `-- name: ListAdminGroupMemberIDs :many
SELECT DISTINCT ug.user_id
FROM user_groups ug
JOIN groups g ON g.id = ug.group_id
WHERE g.grants_admin = TRUE
`

func (q *Queries) ListAdminGroupMemberIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAdminGroupMemberIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT u.id, u.username, u.email, u.name, u.password_hash, u.source, u.is_admin, u.active, u.created_at, u.updated_at, u.ldap_source_id, u.ldap_dn, u.photo, u.photo_mime, u.totp_secret_enc, u.totp_enabled, u.totp_last_counter, u.last_login_at, u.email_verified, u.upstream_source_id, u.external_id, u.must_change_password
FROM users u
JOIN user_groups ug ON ug.user_id = u.id
WHERE ug.group_id = $1
ORDER BY u.username
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Source,
			&i.IsAdmin,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LdapSourceID,
			&i.LdapDn,
			&i.Photo,
			&i.PhotoMime,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.TotpLastCounter,
			&i.LastLoginAt,
			&i.EmailVerified,
			&i.UpstreamSourceID,
			&i.ExternalID,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembersPage = `-- name: ListGroupMembersPage :many
SELECT u.id, u.username, u.email, u.name, u.password_hash, u.source, u.is_admin, u.active, u.created_at, u.updated_at, u.ldap_source_id, u.ldap_dn, u.photo, u.photo_mime, u.totp_secret_enc, u.totp_enabled, u.totp_last_counter, u.last_login_at, u.email_verified, u.upstream_source_id, u.external_id, u.must_change_password
FROM users u
JOIN user_groups ug ON ug.user_id = u.id
WHERE ug.group_id = $1
ORDER BY u.username
LIMIT $3 OFFSET $2
`

type ListGroupMembersPageParams struct {
	GroupID    string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListGroupMembersPage(ctx context.Context, arg ListGroupMembersPageParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembersPage, arg.GroupID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Source,
			&i.IsAdmin,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LdapSourceID,
			&i.LdapDn,
			&i.Photo,
			&i.PhotoMime,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.TotpLastCounter,
			&i.LastLoginAt,
			&i.EmailVerified,
			&i.UpstreamSourceID,
			&i.ExternalID,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsPage = `-- name: ListGroupsPage :many
SELECT g.id, g.name, g.created_at, g.source, g.ldap_source_id, g.grants_admin, g.upstream_source_id, COUNT(ug.user_id) AS member_count
FROM groups g
LEFT JOIN user_groups ug ON ug.group_id = g.id
WHERE lower(g.name) LIKE CAST($1 AS TEXT) ESCAPE '\'
  AND (CAST($2 AS TEXT) = '' OR g.source = CAST($2 AS TEXT))
GROUP BY g.id
ORDER BY g.name
LIMIT $4 OFFSET $3
`

type ListGroupsPageParams struct {
	Pattern    string
	Source     string
	PageOffset int32
	PageLimit  int32
}

type ListGroupsPageRow struct {
	ID               string
	Name             string
	CreatedAt        time.Time
	Source           string
	LdapSourceID     *string
	GrantsAdmin      bool
	UpstreamSourceID *string
	MemberCount      int64
}

func (q *Queries) ListGroupsPage(ctx context.Context, arg ListGroupsPageParams) ([]ListGroupsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsPage,
		arg.Pattern,
		arg.Source,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsPageRow
	for rows.Next() {
		var i ListGroupsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Source,
			&i.LdapSourceID,
			&i.GrantsAdmin,
			&i.UpstreamSourceID,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAdminGroups = `-- name: ListUserAdminGroups :many
SELECT g.id, g.name, g.created_at, g.source, g.ldap_source_id, g.grants_admin, g.upstream_source_id
FROM groups g
JOIN user_groups ug ON ug.group_id = g.id
WHERE ug.user_id = $1 AND g.grants_admin = TRUE
ORDER BY g.name
`

func (q *Queries) ListUserAdminGroups(ctx context.Context, userID string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listUserAdminGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Source,
			&i.LdapSourceID,
			&i.GrantsAdmin,
			&i.UpstreamSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, name, password_hash, source, is_admin, active, created_at, updated_at, ldap_source_id, ldap_dn, photo, photo_mime, totp_secret_enc, totp_enabled, totp_last_counter, last_login_at, email_verified, upstream_source_id, external_id, must_change_password FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Source,
			&i.IsAdmin,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LdapSourceID,
			&i.LdapDn,
			&i.Photo,
			&i.PhotoMime,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.TotpLastCounter,
			&i.LastLoginAt,
			&i.EmailVerified,
			&i.UpstreamSourceID,
			&i.ExternalID,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPage = `-- name: ListUsersPage :many
SELECT id, username, email, name, password_hash, source, is_admin, active, created_at, updated_at, ldap_source_id, ldap_dn, photo, photo_mime, totp_secret_enc, totp_enabled, totp_last_counter, last_login_at, email_verified, upstream_source_id, external_id, must_change_password FROM users
WHERE (lower(username) LIKE CAST($1 AS TEXT) ESCAPE '\'
    OR lower(email) LIKE CAST($1 AS TEXT) ESCAPE '\'
    OR lower(name) LIKE CAST($1 AS TEXT) ESCAPE '\')
  AND (CAST($2 AS TEXT) = '' OR source = CAST($2 AS TEXT))
  AND (CAST($3 AS TEXT) = ''
    OR (CAST($3 AS TEXT) = 'active' AND active)
    OR (CAST($3 AS TEXT) = 'inactive' AND NOT active))
  AND (NOT CAST($4 AS BOOLEAN) OR is_admin
    OR id IN (SELECT ug.user_id FROM user_groups ug JOIN groups g ON g.id = ug.group_id WHERE g.grants_admin))
ORDER BY username
LIMIT $6 OFFSET $5
`

type ListUsersPageParams struct {
	Pattern    string
	Source     string
	Status     string
	AdminsOnly bool
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersPage,
		arg.Pattern,
		arg.Source,
		arg.Status,
		arg.AdminsOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Source,
			&i.IsAdmin,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LdapSourceID,
			&i.LdapDn,
			&i.Photo,
			&i.PhotoMime,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.TotpLastCounter,
			&i.LastLoginAt,
			&i.EmailVerified,
			&i.UpstreamSourceID,
			&i.ExternalID,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserGroup = `-- name: RemoveUserGroup :exec
DELETE FROM user_groups WHERE user_id = $1 AND group_id = $2
`

type RemoveUserGroupParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) RemoveUserGroup(ctx context.Context, arg RemoveUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserGroup, arg.UserID, arg.GroupID)
	return err
}

const renameGroup = `-- name: RenameGroup :exec
UPDATE groups SET name = $1 WHERE id = $2
`

type RenameGroupParams struct {
	Name string
	ID   string
}

func (q *Queries) RenameGroup(ctx context.Context, arg RenameGroupParams) error {
	_, err := q.db.ExecContext(ctx, renameGroup, arg.Name, arg.ID)
	return err
}

const searchGroupCandidates = `-- name: SearchGroupCandidates :many
SELECT u.id, u.username, u.name, u.email
FROM users u
WHERE (lower(u.username) LIKE CAST($1 AS TEXT) ESCAPE '\'
    OR lower(u.name) LIKE CAST($1 AS TEXT) ESCAPE '\'
    OR lower(u.email) LIKE CAST($1 AS TEXT) ESCAPE '\')
  AND u.id NOT IN (SELECT user_id FROM user_groups WHERE group_id = $2)
ORDER BY u.username
LIMIT $3
`

type SearchGroupCandidatesParams struct {
	Pattern    string
	GroupID    string
	MaxResults int32
}

type SearchGroupCandidatesRow struct {
	ID       string
	Username string
	Name     string
	Email    string
}

// Users who are not members of the group yet, matching a type-ahead
// pattern on username, name or email.
func (q *Queries) SearchGroupCandidates(ctx context.Context, arg SearchGroupCandidatesParams) ([]SearchGroupCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchGroupCandidates, arg.Pattern, arg.GroupID, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchGroupCandidatesRow
	for rows.Next() {
		var i SearchGroupCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupGrantsAdmin = `-- name: UpdateGroupGrantsAdmin :exec
UPDATE groups SET grants_admin = $1 WHERE id = $2
`

type UpdateGroupGrantsAdminParams struct {
	GrantsAdmin bool
	ID          string
}

func (q *Queries) UpdateGroupGrantsAdmin(ctx context.Context, arg UpdateGroupGrantsAdminParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupGrantsAdmin, arg.GrantsAdmin, arg.ID)
	return err
}

const updateUserFlags = `-- name: UpdateUserFlags :exec
UPDATE users SET is_admin = $1, active = $2, updated_at = $3 WHERE id = $4
`

type UpdateUserFlagsParams struct {
	IsAdmin   bool
	Active    bool
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateUserFlags(ctx context.Context, arg UpdateUserFlagsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserFlags,
		arg.IsAdmin,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserIdentity = `-- name: UpdateUserIdentity :exec
UPDATE users SET name = $1, email = $2, updated_at = $3 WHERE id = $4
`

type UpdateUserIdentityParams struct {
	Name      string
	Email     string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateUserIdentity(ctx context.Context, arg UpdateUserIdentityParams) error {
	_, err := q.db.ExecContext(ctx, updateUserIdentity,
		arg.Name,
		arg.Email,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserPhoto = `-- name: UpdateUserPhoto :exec
UPDATE users SET photo = $1, photo_mime = $2, updated_at = $3 WHERE id = $4
`

type UpdateUserPhotoParams struct {
	Photo     []byte
	PhotoMime *string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateUserPhoto(ctx context.Context, arg UpdateUserPhotoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPhoto,
		arg.Photo,
		arg.PhotoMime,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
