// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (id, name, slug, kind, description, launch_url, proxy_hosts, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, slug, launch_url, created_at, updated_at, kind, description, icon, icon_mime, proxy_hosts
`

type CreateApplicationParams struct {
	ID          string
	Name        string
	Slug        string
	Kind        string
	Description string
	LaunchUrl   string
	ProxyHosts  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Kind,
		arg.Description,
		arg.LaunchUrl,
		arg.ProxyHosts,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LaunchUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Description,
		&i.Icon,
		&i.IconMime,
		&i.ProxyHosts,
	)
	return i, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (id, application_id, client_id, client_secret_hash, client_secret_enc,
                       redirect_uris, post_logout_redirect_uris, public, access_token_ttl_seconds,
                       refresh_token_ttl_seconds, id_token_ttl_seconds, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, application_id, client_id, client_secret_hash, redirect_uris, post_logout_redirect_uris, public, access_token_ttl_seconds, refresh_token_ttl_seconds, id_token_ttl_seconds, created_at, updated_at, client_secret_enc
`

type CreateProviderParams struct {
	ID                     string
	ApplicationID          string
	ClientID               string
	ClientSecretHash       *string
	ClientSecretEnc        []byte
	RedirectUris           string
	PostLogoutRedirectUris string
	Public                 bool
	AccessTokenTtlSeconds  int64
	RefreshTokenTtlSeconds int64
	IDTokenTtlSeconds      int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRowContext(ctx, createProvider,
		arg.ID,
		arg.ApplicationID,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.ClientSecretEnc,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.Public,
		arg.AccessTokenTtlSeconds,
		arg.RefreshTokenTtlSeconds,
		arg.IDTokenTtlSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.Public,
		&i.AccessTokenTtlSeconds,
		&i.RefreshTokenTtlSeconds,
		&i.IDTokenTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientSecretEnc,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteApplication, id)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, name, slug, launch_url, created_at, updated_at, kind, description, icon, icon_mime, proxy_hosts FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LaunchUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Description,
		&i.Icon,
		&i.IconMime,
		&i.ProxyHosts,
	)
	return i, err
}

const getApplicationIcon = `-- name: GetApplicationIcon :one
SELECT icon, icon_mime FROM applications WHERE id = $1
`

type GetApplicationIconRow struct {
	Icon     []byte
	IconMime *string
}

func (q *Queries) GetApplicationIcon(ctx context.Context, id string) (GetApplicationIconRow, error) {
	row := q.db.QueryRowContext(ctx, getApplicationIcon, id)
	var i GetApplicationIconRow
	err := row.Scan(&i.Icon, &i.IconMime)
	return i, err
}

const getProviderByApplication = `-- name: GetProviderByApplication :one
SELECT id, application_id, client_id, client_secret_hash, redirect_uris, post_logout_redirect_uris, public, access_token_ttl_seconds, refresh_token_ttl_seconds, id_token_ttl_seconds, created_at, updated_at, client_secret_enc FROM providers WHERE application_id = $1
`

func (q *Queries) GetProviderByApplication(ctx context.Context, applicationID string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByApplication, applicationID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.Public,
		&i.AccessTokenTtlSeconds,
		&i.RefreshTokenTtlSeconds,
		&i.IDTokenTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientSecretEnc,
	)
	return i, err
}

const getProviderByClientID = `-- name: GetProviderByClientID :one
SELECT id, application_id, client_id, client_secret_hash, redirect_uris, post_logout_redirect_uris, public, access_token_ttl_seconds, refresh_token_ttl_seconds, id_token_ttl_seconds, created_at, updated_at, client_secret_enc FROM providers WHERE client_id = $1
`

func (q *Queries) GetProviderByClientID(ctx context.Context, clientID string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByClientID, clientID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.Public,
		&i.AccessTokenTtlSeconds,
		&i.RefreshTokenTtlSeconds,
		&i.IDTokenTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientSecretEnc,
	)
	return i, err
}

const listApplicationsAdmin = `-- name: ListApplicationsAdmin :many
SELECT a.id, a.name, a.slug, a.launch_url, a.created_at, a.updated_at, a.kind, a.description, a.icon, a.icon_mime, a.proxy_hosts, p.client_id, p.public
FROM applications a
LEFT JOIN providers p ON p.application_id = a.id
ORDER BY a.name
`

type ListApplicationsAdminRow struct {
	Application Application
	ClientID    *string
	Public      sql.NullBool
}

func (q *Queries) ListApplicationsAdmin(ctx context.Context) ([]ListApplicationsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsAdminRow
	for rows.Next() {
		var i ListApplicationsAdminRow
		if err := rows.Scan(
			&i.Application.ID,
			&i.Application.Name,
			&i.Application.Slug,
			&i.Application.LaunchUrl,
			&i.Application.CreatedAt,
			&i.Application.UpdatedAt,
			&i.Application.Kind,
			&i.Application.Description,
			&i.Application.Icon,
			&i.Application.IconMime,
			&i.Application.ProxyHosts,
			&i.ClientID,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyApplications = `-- name: ListProxyApplications :many
SELECT id, name, slug, launch_url, created_at, updated_at, kind, description, icon, icon_mime, proxy_hosts FROM applications WHERE kind = 'proxy' ORDER BY name
`

func (q *Queries) ListProxyApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listProxyApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LaunchUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.Description,
			&i.Icon,
			&i.IconMime,
			&i.ProxyHosts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE applications
SET name = $1, slug = $2, description = $3, launch_url = $4, proxy_hosts = $5, updated_at = $6
WHERE id = $7
`

type UpdateApplicationParams struct {
	Name        string
	Slug        string
	Description string
	LaunchUrl   string
	ProxyHosts  string
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.ExecContext(ctx, updateApplication,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LaunchUrl,
		arg.ProxyHosts,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateApplicationIcon = `-- name: UpdateApplicationIcon :exec
UPDATE applications SET icon = $1, icon_mime = $2, updated_at = $3 WHERE id = $4
`

type UpdateApplicationIconParams struct {
	Icon      []byte
	IconMime  *string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateApplicationIcon(ctx context.Context, arg UpdateApplicationIconParams) error {
	_, err := q.db.ExecContext(ctx, updateApplicationIcon,
		arg.Icon,
		arg.IconMime,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateProviderRedirects = `-- name: UpdateProviderRedirects :exec
UPDATE providers
SET redirect_uris = $1, post_logout_redirect_uris = $2,
    access_token_ttl_seconds = $3, refresh_token_ttl_seconds = $4, id_token_ttl_seconds = $5,
    updated_at = $6
WHERE id = $7
`

type UpdateProviderRedirectsParams struct {
	RedirectUris           string
	PostLogoutRedirectUris string
	AccessTokenTtlSeconds  int64
	RefreshTokenTtlSeconds int64
	IDTokenTtlSeconds      int64
	UpdatedAt              time.Time
	ID                     string
}

func (q *Queries) UpdateProviderRedirects(ctx context.Context, arg UpdateProviderRedirectsParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderRedirects,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.AccessTokenTtlSeconds,
		arg.RefreshTokenTtlSeconds,
		arg.IDTokenTtlSeconds,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateProviderSecret = `-- name: UpdateProviderSecret :exec
UPDATE providers SET client_secret_hash = $1, client_secret_enc = $2, updated_at = $3 WHERE id = $4
`

type UpdateProviderSecretParams struct {
	ClientSecretHash *string
	ClientSecretEnc  []byte
	UpdatedAt        time.Time
	ID               string
}

func (q *Queries) UpdateProviderSecret(ctx context.Context, arg UpdateProviderSecretParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderSecret,
		arg.ClientSecretHash,
		arg.ClientSecretEnc,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateProviderType = `-- name: UpdateProviderType :exec
UPDATE providers SET public = $1, client_secret_hash = $2, client_secret_enc = $3, updated_at = $4 WHERE id = $5
`

type UpdateProviderTypeParams struct {
	Public           bool
	ClientSecretHash *string
	ClientSecretEnc  []byte
	UpdatedAt        time.Time
	ID               string
}

func (q *Queries) UpdateProviderType(ctx context.Context, arg UpdateProviderTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderType,
		arg.Public,
		arg.ClientSecretHash,
		arg.ClientSecretEnc,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
