// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package sqlcgen

import (
	"context"
	"time"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (id, name, slug, launch_url, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, slug, launch_url, created_at, updated_at
`

type CreateApplicationParams struct {
	ID        string
	Name      string
	Slug      string
	LaunchUrl string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.LaunchUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LaunchUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (id, application_id, client_id, client_secret_hash, redirect_uris,
                       post_logout_redirect_uris, public, access_token_ttl_seconds,
                       refresh_token_ttl_seconds, id_token_ttl_seconds, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, application_id, client_id, client_secret_hash, redirect_uris, post_logout_redirect_uris, public, access_token_ttl_seconds, refresh_token_ttl_seconds, id_token_ttl_seconds, created_at, updated_at
`

type CreateProviderParams struct {
	ID                     string
	ApplicationID          string
	ClientID               string
	ClientSecretHash       *string
	RedirectUris           string
	PostLogoutRedirectUris string
	Public                 bool
	AccessTokenTtlSeconds  int64
	RefreshTokenTtlSeconds int64
	IDTokenTtlSeconds      int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRowContext(ctx, createProvider,
		arg.ID,
		arg.ApplicationID,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.Public,
		arg.AccessTokenTtlSeconds,
		arg.RefreshTokenTtlSeconds,
		arg.IDTokenTtlSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.Public,
		&i.AccessTokenTtlSeconds,
		&i.RefreshTokenTtlSeconds,
		&i.IDTokenTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = ?
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteApplication, id)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, name, slug, launch_url, created_at, updated_at FROM applications WHERE id = ?
`

func (q *Queries) GetApplication(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LaunchUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByApplication = `-- name: GetProviderByApplication :one
SELECT id, application_id, client_id, client_secret_hash, redirect_uris, post_logout_redirect_uris, public, access_token_ttl_seconds, refresh_token_ttl_seconds, id_token_ttl_seconds, created_at, updated_at FROM providers WHERE application_id = ?
`

func (q *Queries) GetProviderByApplication(ctx context.Context, applicationID string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByApplication, applicationID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.Public,
		&i.AccessTokenTtlSeconds,
		&i.RefreshTokenTtlSeconds,
		&i.IDTokenTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByClientID = `-- name: GetProviderByClientID :one
SELECT id, application_id, client_id, client_secret_hash, redirect_uris, post_logout_redirect_uris, public, access_token_ttl_seconds, refresh_token_ttl_seconds, id_token_ttl_seconds, created_at, updated_at FROM providers WHERE client_id = ?
`

func (q *Queries) GetProviderByClientID(ctx context.Context, clientID string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByClientID, clientID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.Public,
		&i.AccessTokenTtlSeconds,
		&i.RefreshTokenTtlSeconds,
		&i.IDTokenTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationsWithProviders = `-- name: ListApplicationsWithProviders :many
SELECT applications.id, applications.name, applications.slug, applications.launch_url, applications.created_at, applications.updated_at, providers.id, providers.application_id, providers.client_id, providers.client_secret_hash, providers.redirect_uris, providers.post_logout_redirect_uris, providers.public, providers.access_token_ttl_seconds, providers.refresh_token_ttl_seconds, providers.id_token_ttl_seconds, providers.created_at, providers.updated_at
FROM applications
JOIN providers ON providers.application_id = applications.id
ORDER BY applications.name
`

type ListApplicationsWithProvidersRow struct {
	Application Application
	Provider    Provider
}

func (q *Queries) ListApplicationsWithProviders(ctx context.Context) ([]ListApplicationsWithProvidersRow, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationsWithProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsWithProvidersRow
	for rows.Next() {
		var i ListApplicationsWithProvidersRow
		if err := rows.Scan(
			&i.Application.ID,
			&i.Application.Name,
			&i.Application.Slug,
			&i.Application.LaunchUrl,
			&i.Application.CreatedAt,
			&i.Application.UpdatedAt,
			&i.Provider.ID,
			&i.Provider.ApplicationID,
			&i.Provider.ClientID,
			&i.Provider.ClientSecretHash,
			&i.Provider.RedirectUris,
			&i.Provider.PostLogoutRedirectUris,
			&i.Provider.Public,
			&i.Provider.AccessTokenTtlSeconds,
			&i.Provider.RefreshTokenTtlSeconds,
			&i.Provider.IDTokenTtlSeconds,
			&i.Provider.CreatedAt,
			&i.Provider.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE applications SET name = ?, slug = ?, launch_url = ?, updated_at = ? WHERE id = ?
`

type UpdateApplicationParams struct {
	Name      string
	Slug      string
	LaunchUrl string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.ExecContext(ctx, updateApplication,
		arg.Name,
		arg.Slug,
		arg.LaunchUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateProviderRedirects = `-- name: UpdateProviderRedirects :exec
UPDATE providers SET redirect_uris = ?, post_logout_redirect_uris = ?, updated_at = ? WHERE id = ?
`

type UpdateProviderRedirectsParams struct {
	RedirectUris           string
	PostLogoutRedirectUris string
	UpdatedAt              time.Time
	ID                     string
}

func (q *Queries) UpdateProviderRedirects(ctx context.Context, arg UpdateProviderRedirectsParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderRedirects,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateProviderSecret = `-- name: UpdateProviderSecret :exec
UPDATE providers SET client_secret_hash = ?, updated_at = ? WHERE id = ?
`

type UpdateProviderSecretParams struct {
	ClientSecretHash *string
	UpdatedAt        time.Time
	ID               string
}

func (q *Queries) UpdateProviderSecret(ctx context.Context, arg UpdateProviderSecretParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderSecret, arg.ClientSecretHash, arg.UpdatedAt, arg.ID)
	return err
}
