// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteAuditBefore = `-- name: DeleteAuditBefore :exec
DELETE FROM audit_log WHERE ts < $1
`

func (q *Queries) DeleteAuditBefore(ctx context.Context, ts time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteAuditBefore, ts)
	return err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (ts, actor, action, object, detail, ip)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditParams struct {
	Ts     time.Time
	Actor  string
	Action string
	Object string
	Detail string
	Ip     string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.Ts,
		arg.Actor,
		arg.Action,
		arg.Object,
		arg.Detail,
		arg.Ip,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, ts, actor, action, object, detail, ip FROM audit_log ORDER BY id DESC LIMIT $1
`

func (q *Queries) ListAudit(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Actor,
			&i.Action,
			&i.Object,
			&i.Detail,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
