// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broker.sql

package sqlcgen

import (
	"context"
	"time"
)

const createLoginRoute = `-- name: CreateLoginRoute :one
INSERT INTO login_routes (id, kind, match_value, target, position, created_at)
VALUES ($1, $2, $3, $4, 0, $5)
RETURNING id, kind, match_value, target, position, created_at
`

type CreateLoginRouteParams struct {
	ID         string
	Kind       string
	MatchValue string
	Target     string
	CreatedAt  time.Time
}

func (q *Queries) CreateLoginRoute(ctx context.Context, arg CreateLoginRouteParams) (LoginRoute, error) {
	row := q.db.QueryRowContext(ctx, createLoginRoute,
		arg.ID,
		arg.Kind,
		arg.MatchValue,
		arg.Target,
		arg.CreatedAt,
	)
	var i LoginRoute
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.MatchValue,
		&i.Target,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createUpstreamGroup = `-- name: CreateUpstreamGroup :one
INSERT INTO groups (id, name, source, upstream_source_id, created_at)
VALUES ($1, $2, 'upstream', $3, $4)
RETURNING id, name, created_at, source, ldap_source_id, grants_admin, upstream_source_id
`

type CreateUpstreamGroupParams struct {
	ID               string
	Name             string
	UpstreamSourceID *string
	CreatedAt        time.Time
}

func (q *Queries) CreateUpstreamGroup(ctx context.Context, arg CreateUpstreamGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createUpstreamGroup,
		arg.ID,
		arg.Name,
		arg.UpstreamSourceID,
		arg.CreatedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Source,
		&i.LdapSourceID,
		&i.GrantsAdmin,
		&i.UpstreamSourceID,
	)
	return i, err
}

const createUpstreamProvider = `-- name: CreateUpstreamProvider :one
INSERT INTO upstream_providers (id, name, issuer, client_id, client_secret_enc, scopes,
                                claim_email, claim_name, claim_groups, allow_signup, enabled,
                                position, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, name, issuer, client_id, client_secret_enc, scopes, claim_email, claim_name, claim_groups, allow_signup, enabled, position, created_at, updated_at
`

type CreateUpstreamProviderParams struct {
	ID              string
	Name            string
	Issuer          string
	ClientID        string
	ClientSecretEnc []byte
	Scopes          string
	ClaimEmail      string
	ClaimName       string
	ClaimGroups     string
	AllowSignup     bool
	Enabled         bool
	Position        int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateUpstreamProvider(ctx context.Context, arg CreateUpstreamProviderParams) (UpstreamProvider, error) {
	row := q.db.QueryRowContext(ctx, createUpstreamProvider,
		arg.ID,
		arg.Name,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.Scopes,
		arg.ClaimEmail,
		arg.ClaimName,
		arg.ClaimGroups,
		arg.AllowSignup,
		arg.Enabled,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UpstreamProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.Scopes,
		&i.ClaimEmail,
		&i.ClaimName,
		&i.ClaimGroups,
		&i.AllowSignup,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUpstreamUser = `-- name: CreateUpstreamUser :one
INSERT INTO users (id, username, email, name, source, upstream_source_id, external_id,
                   email_verified, is_admin, active, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'upstream', $5, $6, $7, FALSE, TRUE, $8, $9)
RETURNING id, username, email, name, password_hash, source, is_admin, active, created_at, updated_at, ldap_source_id, ldap_dn, photo, photo_mime, totp_secret_enc, totp_enabled, totp_last_counter, last_login_at, email_verified, upstream_source_id, external_id, must_change_password, locale
`

type CreateUpstreamUserParams struct {
	ID               string
	Username         string
	Email            string
	Name             string
	UpstreamSourceID *string
	ExternalID       *string
	EmailVerified    bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateUpstreamUser(ctx context.Context, arg CreateUpstreamUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUpstreamUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.UpstreamSourceID,
		arg.ExternalID,
		arg.EmailVerified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Source,
		&i.IsAdmin,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LdapSourceID,
		&i.LdapDn,
		&i.Photo,
		&i.PhotoMime,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.TotpLastCounter,
		&i.LastLoginAt,
		&i.EmailVerified,
		&i.UpstreamSourceID,
		&i.ExternalID,
		&i.MustChangePassword,
		&i.Locale,
	)
	return i, err
}

const deleteLoginRoute = `-- name: DeleteLoginRoute :exec
DELETE FROM login_routes WHERE id = $1
`

func (q *Queries) DeleteLoginRoute(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLoginRoute, id)
	return err
}

const deleteUpstreamProvider = `-- name: DeleteUpstreamProvider :exec
DELETE FROM upstream_providers WHERE id = $1
`

func (q *Queries) DeleteUpstreamProvider(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUpstreamProvider, id)
	return err
}

const deleteUserGroupsFromProvider = `-- name: DeleteUserGroupsFromProvider :exec
DELETE FROM user_groups
WHERE user_id = $1
  AND group_id IN (SELECT id FROM groups WHERE source = 'upstream' AND upstream_source_id = $2)
`

type DeleteUserGroupsFromProviderParams struct {
	UserID           string
	UpstreamSourceID *string
}

func (q *Queries) DeleteUserGroupsFromProvider(ctx context.Context, arg DeleteUserGroupsFromProviderParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserGroupsFromProvider, arg.UserID, arg.UpstreamSourceID)
	return err
}

const getLoginRoute = `-- name: GetLoginRoute :one
SELECT id, kind, match_value, target, position, created_at FROM login_routes WHERE kind = $1 AND match_value = $2
`

type GetLoginRouteParams struct {
	Kind       string
	MatchValue string
}

func (q *Queries) GetLoginRoute(ctx context.Context, arg GetLoginRouteParams) (LoginRoute, error) {
	row := q.db.QueryRowContext(ctx, getLoginRoute, arg.Kind, arg.MatchValue)
	var i LoginRoute
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.MatchValue,
		&i.Target,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getUpstreamProvider = `-- name: GetUpstreamProvider :one
SELECT id, name, issuer, client_id, client_secret_enc, scopes, claim_email, claim_name, claim_groups, allow_signup, enabled, position, created_at, updated_at FROM upstream_providers WHERE id = $1
`

func (q *Queries) GetUpstreamProvider(ctx context.Context, id string) (UpstreamProvider, error) {
	row := q.db.QueryRowContext(ctx, getUpstreamProvider, id)
	var i UpstreamProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.Scopes,
		&i.ClaimEmail,
		&i.ClaimName,
		&i.ClaimGroups,
		&i.AllowSignup,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one

SELECT id, username, email, name, password_hash, source, is_admin, active, created_at, updated_at, ldap_source_id, ldap_dn, photo, photo_mime, totp_secret_enc, totp_enabled, totp_last_counter, last_login_at, email_verified, upstream_source_id, external_id, must_change_password, locale FROM users WHERE upstream_source_id = $1 AND external_id = $2
`

type GetUserByExternalIDParams struct {
	UpstreamSourceID *string
	ExternalID       *string
}

// --- Federated identity on users ----------------------------------------
func (q *Queries) GetUserByExternalID(ctx context.Context, arg GetUserByExternalIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalID, arg.UpstreamSourceID, arg.ExternalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Source,
		&i.IsAdmin,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LdapSourceID,
		&i.LdapDn,
		&i.Photo,
		&i.PhotoMime,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.TotpLastCounter,
		&i.LastLoginAt,
		&i.EmailVerified,
		&i.UpstreamSourceID,
		&i.ExternalID,
		&i.MustChangePassword,
		&i.Locale,
	)
	return i, err
}

const listEnabledUpstreamProviders = `-- name: ListEnabledUpstreamProviders :many
SELECT id, name, issuer, client_id, client_secret_enc, scopes, claim_email, claim_name, claim_groups, allow_signup, enabled, position, created_at, updated_at FROM upstream_providers WHERE enabled = TRUE ORDER BY position, name
`

func (q *Queries) ListEnabledUpstreamProviders(ctx context.Context) ([]UpstreamProvider, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledUpstreamProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpstreamProvider
	for rows.Next() {
		var i UpstreamProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Issuer,
			&i.ClientID,
			&i.ClientSecretEnc,
			&i.Scopes,
			&i.ClaimEmail,
			&i.ClaimName,
			&i.ClaimGroups,
			&i.AllowSignup,
			&i.Enabled,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoginRoutes = `-- name: ListLoginRoutes :many

SELECT id, kind, match_value, target, position, created_at FROM login_routes ORDER BY kind, match_value
`

// --- Login routes (home-realm discovery) --------------------------------
func (q *Queries) ListLoginRoutes(ctx context.Context) ([]LoginRoute, error) {
	rows, err := q.db.QueryContext(ctx, listLoginRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoginRoute
	for rows.Next() {
		var i LoginRoute
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.MatchValue,
			&i.Target,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpstreamProviders = `-- name: ListUpstreamProviders :many
SELECT id, name, issuer, client_id, client_secret_enc, scopes, claim_email, claim_name, claim_groups, allow_signup, enabled, position, created_at, updated_at FROM upstream_providers ORDER BY position, name
`

func (q *Queries) ListUpstreamProviders(ctx context.Context) ([]UpstreamProvider, error) {
	rows, err := q.db.QueryContext(ctx, listUpstreamProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpstreamProvider
	for rows.Next() {
		var i UpstreamProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Issuer,
			&i.ClientID,
			&i.ClientSecretEnc,
			&i.Scopes,
			&i.ClaimEmail,
			&i.ClaimName,
			&i.ClaimGroups,
			&i.AllowSignup,
			&i.Enabled,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultRoute = `-- name: SetDefaultRoute :exec
INSERT INTO login_routes (id, kind, match_value, target, position, created_at)
VALUES ($1, 'default', '', $2, 0, $3)
ON CONFLICT (kind, match_value) DO UPDATE SET target = excluded.target
`

type SetDefaultRouteParams struct {
	ID        string
	Target    string
	CreatedAt time.Time
}

func (q *Queries) SetDefaultRoute(ctx context.Context, arg SetDefaultRouteParams) error {
	_, err := q.db.ExecContext(ctx, setDefaultRoute, arg.ID, arg.Target, arg.CreatedAt)
	return err
}

const setUserUpstreamIdentity = `-- name: SetUserUpstreamIdentity :exec
UPDATE users SET upstream_source_id = $1, external_id = $2, updated_at = $3 WHERE id = $4
`

type SetUserUpstreamIdentityParams struct {
	UpstreamSourceID *string
	ExternalID       *string
	UpdatedAt        time.Time
	ID               string
}

func (q *Queries) SetUserUpstreamIdentity(ctx context.Context, arg SetUserUpstreamIdentityParams) error {
	_, err := q.db.ExecContext(ctx, setUserUpstreamIdentity,
		arg.UpstreamSourceID,
		arg.ExternalID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUpstreamProvider = `-- name: UpdateUpstreamProvider :exec
UPDATE upstream_providers
SET name = $1, issuer = $2, client_id = $3, scopes = $4,
    claim_email = $5, claim_name = $6, claim_groups = $7, allow_signup = $8,
    enabled = $9, updated_at = $10
WHERE id = $11
`

type UpdateUpstreamProviderParams struct {
	Name        string
	Issuer      string
	ClientID    string
	Scopes      string
	ClaimEmail  string
	ClaimName   string
	ClaimGroups string
	AllowSignup bool
	Enabled     bool
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) UpdateUpstreamProvider(ctx context.Context, arg UpdateUpstreamProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateUpstreamProvider,
		arg.Name,
		arg.Issuer,
		arg.ClientID,
		arg.Scopes,
		arg.ClaimEmail,
		arg.ClaimName,
		arg.ClaimGroups,
		arg.AllowSignup,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUpstreamProviderSecret = `-- name: UpdateUpstreamProviderSecret :exec
UPDATE upstream_providers SET client_secret_enc = $1, updated_at = $2 WHERE id = $3
`

type UpdateUpstreamProviderSecretParams struct {
	ClientSecretEnc []byte
	UpdatedAt       time.Time
	ID              string
}

func (q *Queries) UpdateUpstreamProviderSecret(ctx context.Context, arg UpdateUpstreamProviderSecretParams) error {
	_, err := q.db.ExecContext(ctx, updateUpstreamProviderSecret, arg.ClientSecretEnc, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users SET name = $1, updated_at = $2 WHERE id = $3
`

type UpdateUserDisplayNameParams struct {
	Name      string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDisplayName, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}
