// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_tokens.sql

package sqlcgen

import (
	"context"
	"time"
)

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO email_tokens (token_hash, purpose, user_id, email, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateEmailTokenParams struct {
	TokenHash string
	Purpose   string
	UserID    string
	Email     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.db.ExecContext(ctx, createEmailToken,
		arg.TokenHash,
		arg.Purpose,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteEmailToken = `-- name: DeleteEmailToken :exec
DELETE FROM email_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteEmailToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteEmailToken, tokenHash)
	return err
}

const deleteEmailTokensByUserPurpose = `-- name: DeleteEmailTokensByUserPurpose :exec
DELETE FROM email_tokens WHERE user_id = $1 AND purpose = $2
`

type DeleteEmailTokensByUserPurposeParams struct {
	UserID  string
	Purpose string
}

func (q *Queries) DeleteEmailTokensByUserPurpose(ctx context.Context, arg DeleteEmailTokensByUserPurposeParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmailTokensByUserPurpose, arg.UserID, arg.Purpose)
	return err
}

const deleteExpiredEmailTokens = `-- name: DeleteExpiredEmailTokens :exec
DELETE FROM email_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredEmailTokens(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredEmailTokens, expiresAt)
	return err
}

const getEmailToken = `-- name: GetEmailToken :one
SELECT token_hash, purpose, user_id, email, expires_at, created_at FROM email_tokens WHERE token_hash = $1
`

func (q *Queries) GetEmailToken(ctx context.Context, tokenHash string) (EmailToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailToken, tokenHash)
	var i EmailToken
	err := row.Scan(
		&i.TokenHash,
		&i.Purpose,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
