// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package sqlcgen

import (
	"context"
	"time"
)

const clearBrandLogo = `-- name: ClearBrandLogo :exec
UPDATE instance_settings SET logo = NULL, logo_mime = NULL, updated_at = $1 WHERE id = 1
`

func (q *Queries) ClearBrandLogo(ctx context.Context, updatedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, clearBrandLogo, updatedAt)
	return err
}

const clearLoginBackground = `-- name: ClearLoginBackground :exec
UPDATE instance_settings SET login_background = NULL, login_background_mime = NULL, updated_at = $1 WHERE id = 1
`

func (q *Queries) ClearLoginBackground(ctx context.Context, updatedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, clearLoginBackground, updatedAt)
	return err
}

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT id, brand_name, logo, logo_mime, updated_at, login_background, login_background_mime, mfa_policy, new_device_alerts FROM instance_settings WHERE id = 1
`

func (q *Queries) GetInstanceSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, getInstanceSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.BrandName,
		&i.Logo,
		&i.LogoMime,
		&i.UpdatedAt,
		&i.LoginBackground,
		&i.LoginBackgroundMime,
		&i.MfaPolicy,
		&i.NewDeviceAlerts,
	)
	return i, err
}

const setBrandLogo = `-- name: SetBrandLogo :exec
UPDATE instance_settings SET logo = $1, logo_mime = $2, updated_at = $3 WHERE id = 1
`

type SetBrandLogoParams struct {
	Logo      []byte
	LogoMime  *string
	UpdatedAt time.Time
}

func (q *Queries) SetBrandLogo(ctx context.Context, arg SetBrandLogoParams) error {
	_, err := q.db.ExecContext(ctx, setBrandLogo, arg.Logo, arg.LogoMime, arg.UpdatedAt)
	return err
}

const setBrandName = `-- name: SetBrandName :exec
UPDATE instance_settings SET brand_name = $1, updated_at = $2 WHERE id = 1
`

type SetBrandNameParams struct {
	BrandName string
	UpdatedAt time.Time
}

func (q *Queries) SetBrandName(ctx context.Context, arg SetBrandNameParams) error {
	_, err := q.db.ExecContext(ctx, setBrandName, arg.BrandName, arg.UpdatedAt)
	return err
}

const setLoginBackground = `-- name: SetLoginBackground :exec
UPDATE instance_settings SET login_background = $1, login_background_mime = $2, updated_at = $3 WHERE id = 1
`

type SetLoginBackgroundParams struct {
	LoginBackground     []byte
	LoginBackgroundMime *string
	UpdatedAt           time.Time
}

func (q *Queries) SetLoginBackground(ctx context.Context, arg SetLoginBackgroundParams) error {
	_, err := q.db.ExecContext(ctx, setLoginBackground, arg.LoginBackground, arg.LoginBackgroundMime, arg.UpdatedAt)
	return err
}

const setMFAPolicy = `-- name: SetMFAPolicy :exec
UPDATE instance_settings SET mfa_policy = $1, updated_at = $2 WHERE id = 1
`

type SetMFAPolicyParams struct {
	MfaPolicy string
	UpdatedAt time.Time
}

func (q *Queries) SetMFAPolicy(ctx context.Context, arg SetMFAPolicyParams) error {
	_, err := q.db.ExecContext(ctx, setMFAPolicy, arg.MfaPolicy, arg.UpdatedAt)
	return err
}

const setNewDeviceAlerts = `-- name: SetNewDeviceAlerts :exec
UPDATE instance_settings SET new_device_alerts = $1, updated_at = $2 WHERE id = 1
`

type SetNewDeviceAlertsParams struct {
	NewDeviceAlerts bool
	UpdatedAt       time.Time
}

func (q *Queries) SetNewDeviceAlerts(ctx context.Context, arg SetNewDeviceAlertsParams) error {
	_, err := q.db.ExecContext(ctx, setNewDeviceAlerts, arg.NewDeviceAlerts, arg.UpdatedAt)
	return err
}
