// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ldap.sql

package sqlcgen

import (
	"context"
	"time"
)

const addUserGroup = `-- name: AddUserGroup :exec
INSERT INTO user_groups (user_id, group_id) VALUES ($1, $2)
`

type AddUserGroupParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) AddUserGroup(ctx context.Context, arg AddUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserGroup, arg.UserID, arg.GroupID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, source, ldap_source_id, created_at) VALUES ($1, $2, $3, $4, $5) RETURNING id, name, created_at, source, ldap_source_id, grants_admin, upstream_source_id
`

type CreateGroupParams struct {
	ID           string
	Name         string
	Source       string
	LdapSourceID *string
	CreatedAt    time.Time
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.LdapSourceID,
		arg.CreatedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Source,
		&i.LdapSourceID,
		&i.GrantsAdmin,
		&i.UpstreamSourceID,
	)
	return i, err
}

const createLdapSource = `-- name: CreateLdapSource :one
INSERT INTO ldap_sources (id, name, url, start_tls, skip_tls_verify, bind_dn, bind_password_enc,
                          base_dn, user_filter, username_attr, email_attr, name_attr, photo_attr,
                          group_filter, group_name_attr, password_writeback, password_reset, enabled,
                          position, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
RETURNING id, name, url, start_tls, skip_tls_verify, bind_dn, bind_password_enc, base_dn, user_filter, username_attr, email_attr, name_attr, group_filter, group_name_attr, enabled, position, created_at, updated_at, password_writeback, photo_attr, password_reset
`

type CreateLdapSourceParams struct {
	ID                string
	Name              string
	Url               string
	StartTls          bool
	SkipTlsVerify     bool
	BindDn            string
	BindPasswordEnc   []byte
	BaseDn            string
	UserFilter        string
	UsernameAttr      string
	EmailAttr         string
	NameAttr          string
	PhotoAttr         string
	GroupFilter       string
	GroupNameAttr     string
	PasswordWriteback bool
	PasswordReset     bool
	Enabled           bool
	Position          int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreateLdapSource(ctx context.Context, arg CreateLdapSourceParams) (LdapSource, error) {
	row := q.db.QueryRowContext(ctx, createLdapSource,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.StartTls,
		arg.SkipTlsVerify,
		arg.BindDn,
		arg.BindPasswordEnc,
		arg.BaseDn,
		arg.UserFilter,
		arg.UsernameAttr,
		arg.EmailAttr,
		arg.NameAttr,
		arg.PhotoAttr,
		arg.GroupFilter,
		arg.GroupNameAttr,
		arg.PasswordWriteback,
		arg.PasswordReset,
		arg.Enabled,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LdapSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.StartTls,
		&i.SkipTlsVerify,
		&i.BindDn,
		&i.BindPasswordEnc,
		&i.BaseDn,
		&i.UserFilter,
		&i.UsernameAttr,
		&i.EmailAttr,
		&i.NameAttr,
		&i.GroupFilter,
		&i.GroupNameAttr,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordWriteback,
		&i.PhotoAttr,
		&i.PasswordReset,
	)
	return i, err
}

const deleteLdapSource = `-- name: DeleteLdapSource :exec
DELETE FROM ldap_sources WHERE id = $1
`

func (q *Queries) DeleteLdapSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLdapSource, id)
	return err
}

const deleteUserGroupsFromSource = `-- name: DeleteUserGroupsFromSource :exec
DELETE FROM user_groups
WHERE user_id = $1
  AND group_id IN (SELECT id FROM groups WHERE source = 'ldap' AND ldap_source_id = $2)
`

type DeleteUserGroupsFromSourceParams struct {
	UserID       string
	LdapSourceID *string
}

func (q *Queries) DeleteUserGroupsFromSource(ctx context.Context, arg DeleteUserGroupsFromSourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserGroupsFromSource, arg.UserID, arg.LdapSourceID)
	return err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, created_at, source, ldap_source_id, grants_admin, upstream_source_id FROM groups WHERE name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Source,
		&i.LdapSourceID,
		&i.GrantsAdmin,
		&i.UpstreamSourceID,
	)
	return i, err
}

const getLdapSource = `-- name: GetLdapSource :one
SELECT id, name, url, start_tls, skip_tls_verify, bind_dn, bind_password_enc, base_dn, user_filter, username_attr, email_attr, name_attr, group_filter, group_name_attr, enabled, position, created_at, updated_at, password_writeback, photo_attr, password_reset FROM ldap_sources WHERE id = $1
`

func (q *Queries) GetLdapSource(ctx context.Context, id string) (LdapSource, error) {
	row := q.db.QueryRowContext(ctx, getLdapSource, id)
	var i LdapSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.StartTls,
		&i.SkipTlsVerify,
		&i.BindDn,
		&i.BindPasswordEnc,
		&i.BaseDn,
		&i.UserFilter,
		&i.UsernameAttr,
		&i.EmailAttr,
		&i.NameAttr,
		&i.GroupFilter,
		&i.GroupNameAttr,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordWriteback,
		&i.PhotoAttr,
		&i.PasswordReset,
	)
	return i, err
}

const listEnabledLdapSources = `-- name: ListEnabledLdapSources :many
SELECT id, name, url, start_tls, skip_tls_verify, bind_dn, bind_password_enc, base_dn, user_filter, username_attr, email_attr, name_attr, group_filter, group_name_attr, enabled, position, created_at, updated_at, password_writeback, photo_attr, password_reset FROM ldap_sources WHERE enabled = TRUE ORDER BY position, name
`

func (q *Queries) ListEnabledLdapSources(ctx context.Context) ([]LdapSource, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledLdapSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LdapSource
	for rows.Next() {
		var i LdapSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.StartTls,
			&i.SkipTlsVerify,
			&i.BindDn,
			&i.BindPasswordEnc,
			&i.BaseDn,
			&i.UserFilter,
			&i.UsernameAttr,
			&i.EmailAttr,
			&i.NameAttr,
			&i.GroupFilter,
			&i.GroupNameAttr,
			&i.Enabled,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordWriteback,
			&i.PhotoAttr,
			&i.PasswordReset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLdapSources = `-- name: ListLdapSources :many
SELECT id, name, url, start_tls, skip_tls_verify, bind_dn, bind_password_enc, base_dn, user_filter, username_attr, email_attr, name_attr, group_filter, group_name_attr, enabled, position, created_at, updated_at, password_writeback, photo_attr, password_reset FROM ldap_sources ORDER BY position, name
`

func (q *Queries) ListLdapSources(ctx context.Context) ([]LdapSource, error) {
	rows, err := q.db.QueryContext(ctx, listLdapSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LdapSource
	for rows.Next() {
		var i LdapSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.StartTls,
			&i.SkipTlsVerify,
			&i.BindDn,
			&i.BindPasswordEnc,
			&i.BaseDn,
			&i.UserFilter,
			&i.UsernameAttr,
			&i.EmailAttr,
			&i.NameAttr,
			&i.GroupFilter,
			&i.GroupNameAttr,
			&i.Enabled,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordWriteback,
			&i.PhotoAttr,
			&i.PasswordReset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLdapSource = `-- name: UpdateLdapSource :exec
UPDATE ldap_sources
SET name = $1, url = $2, start_tls = $3, skip_tls_verify = $4, bind_dn = $5, base_dn = $6,
    user_filter = $7, username_attr = $8, email_attr = $9, name_attr = $10, photo_attr = $11,
    group_filter = $12, group_name_attr = $13, password_writeback = $14, password_reset = $15,
    enabled = $16, updated_at = $17
WHERE id = $18
`

type UpdateLdapSourceParams struct {
	Name              string
	Url               string
	StartTls          bool
	SkipTlsVerify     bool
	BindDn            string
	BaseDn            string
	UserFilter        string
	UsernameAttr      string
	EmailAttr         string
	NameAttr          string
	PhotoAttr         string
	GroupFilter       string
	GroupNameAttr     string
	PasswordWriteback bool
	PasswordReset     bool
	Enabled           bool
	UpdatedAt         time.Time
	ID                string
}

func (q *Queries) UpdateLdapSource(ctx context.Context, arg UpdateLdapSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateLdapSource,
		arg.Name,
		arg.Url,
		arg.StartTls,
		arg.SkipTlsVerify,
		arg.BindDn,
		arg.BaseDn,
		arg.UserFilter,
		arg.UsernameAttr,
		arg.EmailAttr,
		arg.NameAttr,
		arg.PhotoAttr,
		arg.GroupFilter,
		arg.GroupNameAttr,
		arg.PasswordWriteback,
		arg.PasswordReset,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateLdapSourceBindPassword = `-- name: UpdateLdapSourceBindPassword :exec
UPDATE ldap_sources SET bind_password_enc = $1, updated_at = $2 WHERE id = $3
`

type UpdateLdapSourceBindPasswordParams struct {
	BindPasswordEnc []byte
	UpdatedAt       time.Time
	ID              string
}

func (q *Queries) UpdateLdapSourceBindPassword(ctx context.Context, arg UpdateLdapSourceBindPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateLdapSourceBindPassword, arg.BindPasswordEnc, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserLdapProfile = `-- name: UpdateUserLdapProfile :exec
UPDATE users SET email = $1, name = $2, ldap_dn = $3, photo = $4, photo_mime = $5, updated_at = $6 WHERE id = $7
`

type UpdateUserLdapProfileParams struct {
	Email     string
	Name      string
	LdapDn    *string
	Photo     []byte
	PhotoMime *string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateUserLdapProfile(ctx context.Context, arg UpdateUserLdapProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLdapProfile,
		arg.Email,
		arg.Name,
		arg.LdapDn,
		arg.Photo,
		arg.PhotoMime,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
