// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ldap.sql

package sqlcgen

import (
	"context"
	"time"
)

const addUserGroup = `-- name: AddUserGroup :exec
INSERT INTO user_groups (user_id, group_id) VALUES (?, ?)
`

type AddUserGroupParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) AddUserGroup(ctx context.Context, arg AddUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserGroup, arg.UserID, arg.GroupID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, created_at) VALUES (?, ?, ?) RETURNING id, name, created_at
`

type CreateGroupParams struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.ID, arg.Name, arg.CreatedAt)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createLdapSource = `-- name: CreateLdapSource :one
INSERT INTO ldap_sources (id, name, url, start_tls, skip_tls_verify, bind_dn, bind_password_enc,
                          base_dn, user_filter, username_attr, email_attr, name_attr,
                          group_filter, group_name_attr, enabled, position, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, url, start_tls, skip_tls_verify, bind_dn, bind_password_enc, base_dn, user_filter, username_attr, email_attr, name_attr, group_filter, group_name_attr, enabled, position, created_at, updated_at
`

type CreateLdapSourceParams struct {
	ID              string
	Name            string
	Url             string
	StartTls        bool
	SkipTlsVerify   bool
	BindDn          string
	BindPasswordEnc []byte
	BaseDn          string
	UserFilter      string
	UsernameAttr    string
	EmailAttr       string
	NameAttr        string
	GroupFilter     string
	GroupNameAttr   string
	Enabled         bool
	Position        int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateLdapSource(ctx context.Context, arg CreateLdapSourceParams) (LdapSource, error) {
	row := q.db.QueryRowContext(ctx, createLdapSource,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.StartTls,
		arg.SkipTlsVerify,
		arg.BindDn,
		arg.BindPasswordEnc,
		arg.BaseDn,
		arg.UserFilter,
		arg.UsernameAttr,
		arg.EmailAttr,
		arg.NameAttr,
		arg.GroupFilter,
		arg.GroupNameAttr,
		arg.Enabled,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LdapSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.StartTls,
		&i.SkipTlsVerify,
		&i.BindDn,
		&i.BindPasswordEnc,
		&i.BaseDn,
		&i.UserFilter,
		&i.UsernameAttr,
		&i.EmailAttr,
		&i.NameAttr,
		&i.GroupFilter,
		&i.GroupNameAttr,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLdapSource = `-- name: DeleteLdapSource :exec
DELETE FROM ldap_sources WHERE id = ?
`

func (q *Queries) DeleteLdapSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLdapSource, id)
	return err
}

const deleteUserGroups = `-- name: DeleteUserGroups :exec
DELETE FROM user_groups WHERE user_id = ?
`

func (q *Queries) DeleteUserGroups(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserGroups, userID)
	return err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, created_at FROM groups WHERE name = ?
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getLdapSource = `-- name: GetLdapSource :one
SELECT id, name, url, start_tls, skip_tls_verify, bind_dn, bind_password_enc, base_dn, user_filter, username_attr, email_attr, name_attr, group_filter, group_name_attr, enabled, position, created_at, updated_at FROM ldap_sources WHERE id = ?
`

func (q *Queries) GetLdapSource(ctx context.Context, id string) (LdapSource, error) {
	row := q.db.QueryRowContext(ctx, getLdapSource, id)
	var i LdapSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.StartTls,
		&i.SkipTlsVerify,
		&i.BindDn,
		&i.BindPasswordEnc,
		&i.BaseDn,
		&i.UserFilter,
		&i.UsernameAttr,
		&i.EmailAttr,
		&i.NameAttr,
		&i.GroupFilter,
		&i.GroupNameAttr,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledLdapSources = `-- name: ListEnabledLdapSources :many
SELECT id, name, url, start_tls, skip_tls_verify, bind_dn, bind_password_enc, base_dn, user_filter, username_attr, email_attr, name_attr, group_filter, group_name_attr, enabled, position, created_at, updated_at FROM ldap_sources WHERE enabled = TRUE ORDER BY position, name
`

func (q *Queries) ListEnabledLdapSources(ctx context.Context) ([]LdapSource, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledLdapSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LdapSource
	for rows.Next() {
		var i LdapSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.StartTls,
			&i.SkipTlsVerify,
			&i.BindDn,
			&i.BindPasswordEnc,
			&i.BaseDn,
			&i.UserFilter,
			&i.UsernameAttr,
			&i.EmailAttr,
			&i.NameAttr,
			&i.GroupFilter,
			&i.GroupNameAttr,
			&i.Enabled,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLdapSources = `-- name: ListLdapSources :many
SELECT id, name, url, start_tls, skip_tls_verify, bind_dn, bind_password_enc, base_dn, user_filter, username_attr, email_attr, name_attr, group_filter, group_name_attr, enabled, position, created_at, updated_at FROM ldap_sources ORDER BY position, name
`

func (q *Queries) ListLdapSources(ctx context.Context) ([]LdapSource, error) {
	rows, err := q.db.QueryContext(ctx, listLdapSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LdapSource
	for rows.Next() {
		var i LdapSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.StartTls,
			&i.SkipTlsVerify,
			&i.BindDn,
			&i.BindPasswordEnc,
			&i.BaseDn,
			&i.UserFilter,
			&i.UsernameAttr,
			&i.EmailAttr,
			&i.NameAttr,
			&i.GroupFilter,
			&i.GroupNameAttr,
			&i.Enabled,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLdapSource = `-- name: UpdateLdapSource :exec
UPDATE ldap_sources
SET name = ?, url = ?, start_tls = ?, skip_tls_verify = ?, bind_dn = ?, base_dn = ?,
    user_filter = ?, username_attr = ?, email_attr = ?, name_attr = ?,
    group_filter = ?, group_name_attr = ?, enabled = ?, updated_at = ?
WHERE id = ?
`

type UpdateLdapSourceParams struct {
	Name          string
	Url           string
	StartTls      bool
	SkipTlsVerify bool
	BindDn        string
	BaseDn        string
	UserFilter    string
	UsernameAttr  string
	EmailAttr     string
	NameAttr      string
	GroupFilter   string
	GroupNameAttr string
	Enabled       bool
	UpdatedAt     time.Time
	ID            string
}

func (q *Queries) UpdateLdapSource(ctx context.Context, arg UpdateLdapSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateLdapSource,
		arg.Name,
		arg.Url,
		arg.StartTls,
		arg.SkipTlsVerify,
		arg.BindDn,
		arg.BaseDn,
		arg.UserFilter,
		arg.UsernameAttr,
		arg.EmailAttr,
		arg.NameAttr,
		arg.GroupFilter,
		arg.GroupNameAttr,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateLdapSourceBindPassword = `-- name: UpdateLdapSourceBindPassword :exec
UPDATE ldap_sources SET bind_password_enc = ?, updated_at = ? WHERE id = ?
`

type UpdateLdapSourceBindPasswordParams struct {
	BindPasswordEnc []byte
	UpdatedAt       time.Time
	ID              string
}

func (q *Queries) UpdateLdapSourceBindPassword(ctx context.Context, arg UpdateLdapSourceBindPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateLdapSourceBindPassword, arg.BindPasswordEnc, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserLdapProfile = `-- name: UpdateUserLdapProfile :exec
UPDATE users SET email = ?, name = ?, ldap_dn = ?, updated_at = ? WHERE id = ?
`

type UpdateUserLdapProfileParams struct {
	Email     string
	Name      string
	LdapDn    *string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateUserLdapProfile(ctx context.Context, arg UpdateUserLdapProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLdapProfile,
		arg.Email,
		arg.Name,
		arg.LdapDn,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
