// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const claimUserTOTPCounter = `-- name: ClaimUserTOTPCounter :execrows
UPDATE users SET totp_last_counter = $1, updated_at = $2
WHERE id = $3 AND totp_last_counter < $1
`

type ClaimUserTOTPCounterParams struct {
	TotpLastCounter int64
	UpdatedAt       time.Time
	ID              string
}

// Atomically advances the last accepted TOTP counter. Zero rows means
// this time step (or a later one) was already consumed: a replay.
func (q *Queries) ClaimUserTOTPCounter(ctx context.Context, arg ClaimUserTOTPCounterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimUserTOTPCounter, arg.TotpLastCounter, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT COUNT(*) FROM mfa_recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO mfa_recovery_codes (id, user_id, code_hash, created_at) VALUES ($1, $2, $3, $4)
`

type CreateRecoveryCodeParams struct {
	ID        string
	UserID    string
	CodeHash  string
	CreatedAt time.Time
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, createRecoveryCode,
		arg.ID,
		arg.UserID,
		arg.CodeHash,
		arg.CreatedAt,
	)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM mfa_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodes, userID)
	return err
}

const disableUserTOTP = `-- name: DisableUserTOTP :exec
UPDATE users SET totp_secret_enc = NULL, totp_enabled = FALSE, updated_at = $1 WHERE id = $2
`

type DisableUserTOTPParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) DisableUserTOTP(ctx context.Context, arg DisableUserTOTPParams) error {
	_, err := q.db.ExecContext(ctx, disableUserTOTP, arg.UpdatedAt, arg.ID)
	return err
}

const listUnusedRecoveryCodes = `-- name: ListUnusedRecoveryCodes :many
SELECT id, user_id, code_hash, used_at, created_at FROM mfa_recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) ListUnusedRecoveryCodes(ctx context.Context, userID string) ([]MfaRecoveryCode, error) {
	rows, err := q.db.QueryContext(ctx, listUnusedRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MfaRecoveryCode
	for rows.Next() {
		var i MfaRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE mfa_recovery_codes SET used_at = $1 WHERE id = $2
`

type MarkRecoveryCodeUsedParams struct {
	UsedAt sql.NullTime
	ID     string
}

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) error {
	_, err := q.db.ExecContext(ctx, markRecoveryCodeUsed, arg.UsedAt, arg.ID)
	return err
}

const setUserTOTP = `-- name: SetUserTOTP :exec
UPDATE users SET totp_secret_enc = $1, totp_enabled = $2, totp_last_counter = $3, updated_at = $4 WHERE id = $5
`

type SetUserTOTPParams struct {
	TotpSecretEnc   []byte
	TotpEnabled     bool
	TotpLastCounter int64
	UpdatedAt       time.Time
	ID              string
}

func (q *Queries) SetUserTOTP(ctx context.Context, arg SetUserTOTPParams) error {
	_, err := q.db.ExecContext(ctx, setUserTOTP,
		arg.TotpSecretEnc,
		arg.TotpEnabled,
		arg.TotpLastCounter,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
