// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type AccessToken struct {
	ID             string
	UserID         string
	ClientID       string
	Scopes         string
	Audience       string
	RefreshTokenID *string
	ExpiresAt      time.Time
	CreatedAt      time.Time
}

type Application struct {
	ID        string
	Name      string
	Slug      string
	LaunchUrl string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AuthRequest struct {
	ID        string
	Code      *string
	Request   string
	CreatedAt time.Time
}

type Group struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type LdapSource struct {
	ID              string
	Name            string
	Url             string
	StartTls        bool
	SkipTlsVerify   bool
	BindDn          string
	BindPasswordEnc []byte
	BaseDn          string
	UserFilter      string
	UsernameAttr    string
	EmailAttr       string
	NameAttr        string
	GroupFilter     string
	GroupNameAttr   string
	Enabled         bool
	Position        int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Provider struct {
	ID                     string
	ApplicationID          string
	ClientID               string
	ClientSecretHash       *string
	RedirectUris           string
	PostLogoutRedirectUris string
	Public                 bool
	AccessTokenTtlSeconds  int64
	RefreshTokenTtlSeconds int64
	IDTokenTtlSeconds      int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type RefreshToken struct {
	ID        string
	UserID    string
	ClientID  string
	Scopes    string
	Audience  string
	Amr       string
	AuthTime  time.Time
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type SigningKey struct {
	ID            string
	Alg           string
	PrivateKeyEnc []byte
	PublicKeyDer  []byte
	Active        bool
	CreatedAt     time.Time
}

type User struct {
	ID           string
	Username     string
	Email        string
	Name         string
	PasswordHash *string
	Source       string
	IsAdmin      bool
	Active       bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LdapSourceID *string
	LdapDn       *string
}

type UserGroup struct {
	UserID  string
	GroupID string
}
