// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type AccessToken struct {
	ID             string
	UserID         string
	ClientID       string
	Scopes         string
	Audience       string
	RefreshTokenID *string
	ExpiresAt      time.Time
	CreatedAt      time.Time
}

type AppPolicy struct {
	ApplicationID string
	GroupID       string
}

type Application struct {
	ID          string
	Name        string
	Slug        string
	LaunchUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Kind        string
	Description string
	Icon        []byte
	IconMime    *string
	ProxyHosts  string
}

type AuditLog struct {
	ID     int64
	Ts     time.Time
	Actor  string
	Action string
	Object string
	Detail string
	Ip     string
}

type AuthRequest struct {
	ID        string
	Code      *string
	Request   string
	CreatedAt time.Time
}

type EmailToken struct {
	TokenHash string
	Purpose   string
	UserID    string
	Email     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Group struct {
	ID           string
	Name         string
	CreatedAt    time.Time
	Source       string
	LdapSourceID *string
	GrantsAdmin  bool
}

type InstanceSetting struct {
	ID        int32
	BrandName string
	Logo      []byte
	LogoMime  *string
	UpdatedAt time.Time
}

type LdapSource struct {
	ID                string
	Name              string
	Url               string
	StartTls          bool
	SkipTlsVerify     bool
	BindDn            string
	BindPasswordEnc   []byte
	BaseDn            string
	UserFilter        string
	UsernameAttr      string
	EmailAttr         string
	NameAttr          string
	GroupFilter       string
	GroupNameAttr     string
	Enabled           bool
	Position          int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	PasswordWriteback bool
	PhotoAttr         string
	PasswordReset     bool
}

type LoginRoute struct {
	ID         string
	Kind       string
	MatchValue string
	Target     string
	Position   int32
	CreatedAt  time.Time
}

type MfaRecoveryCode struct {
	ID        string
	UserID    string
	CodeHash  string
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type Provider struct {
	ID                     string
	ApplicationID          string
	ClientID               string
	ClientSecretHash       *string
	RedirectUris           string
	PostLogoutRedirectUris string
	Public                 bool
	AccessTokenTtlSeconds  int64
	RefreshTokenTtlSeconds int64
	IDTokenTtlSeconds      int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	ClientSecretEnc        []byte
}

type RefreshToken struct {
	ID        string
	UserID    string
	ClientID  string
	Scopes    string
	Audience  string
	Amr       string
	AuthTime  time.Time
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type SigningKey struct {
	ID            string
	Alg           string
	PrivateKeyEnc []byte
	PublicKeyDer  []byte
	Active        bool
	CreatedAt     time.Time
}

type SmtpSetting struct {
	ID          int32
	Enabled     bool
	Host        string
	Port        int32
	Username    string
	PasswordEnc []byte
	FromAddress string
	FromName    string
	Encryption  string
	UpdatedAt   time.Time
}

type UpstreamProvider struct {
	ID              string
	Name            string
	Issuer          string
	ClientID        string
	ClientSecretEnc []byte
	Scopes          string
	ClaimEmail      string
	ClaimName       string
	ClaimGroups     string
	AllowSignup     bool
	Enabled         bool
	Position        int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type User struct {
	ID               string
	Username         string
	Email            string
	Name             string
	PasswordHash     *string
	Source           string
	IsAdmin          bool
	Active           bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LdapSourceID     *string
	LdapDn           *string
	Photo            []byte
	PhotoMime        *string
	TotpSecretEnc    []byte
	TotpEnabled      bool
	TotpLastCounter  int64
	LastLoginAt      sql.NullTime
	EmailVerified    bool
	UpstreamSourceID *string
	ExternalID       *string
}

type UserGroup struct {
	UserID  string
	GroupID string
}

type WebauthnCredential struct {
	ID           string
	UserID       string
	CredentialID string
	Name         string
	Data         string
	CreatedAt    time.Time
	LastUsedAt   sql.NullTime
}
