// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type AccessToken struct {
	ID             string
	UserID         string
	ClientID       string
	Scopes         string
	Audience       string
	RefreshTokenID *string
	ExpiresAt      time.Time
	CreatedAt      time.Time
}

type AppPolicy struct {
	ApplicationID string
	GroupID       string
}

type Application struct {
	ID          string
	Name        string
	Slug        string
	LaunchUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Kind        string
	Description string
	Icon        []byte
	IconMime    *string
	ProxyHosts  string
}

type AuditLog struct {
	ID     int64
	Ts     time.Time
	Actor  string
	Action string
	Object string
	Detail string
	Ip     string
}

type AuthRequest struct {
	ID        string
	Code      *string
	Request   string
	CreatedAt time.Time
}

type Group struct {
	ID           string
	Name         string
	CreatedAt    time.Time
	Source       string
	LdapSourceID *string
	GrantsAdmin  bool
}

type LdapSource struct {
	ID                string
	Name              string
	Url               string
	StartTls          bool
	SkipTlsVerify     bool
	BindDn            string
	BindPasswordEnc   []byte
	BaseDn            string
	UserFilter        string
	UsernameAttr      string
	EmailAttr         string
	NameAttr          string
	GroupFilter       string
	GroupNameAttr     string
	Enabled           bool
	Position          int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	PasswordWriteback bool
	PhotoAttr         string
}

type MfaRecoveryCode struct {
	ID        string
	UserID    string
	CodeHash  string
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type Provider struct {
	ID                     string
	ApplicationID          string
	ClientID               string
	ClientSecretHash       *string
	RedirectUris           string
	PostLogoutRedirectUris string
	Public                 bool
	AccessTokenTtlSeconds  int64
	RefreshTokenTtlSeconds int64
	IDTokenTtlSeconds      int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	ClientSecretEnc        []byte
}

type RefreshToken struct {
	ID        string
	UserID    string
	ClientID  string
	Scopes    string
	Audience  string
	Amr       string
	AuthTime  time.Time
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type SigningKey struct {
	ID            string
	Alg           string
	PrivateKeyEnc []byte
	PublicKeyDer  []byte
	Active        bool
	CreatedAt     time.Time
}

type User struct {
	ID            string
	Username      string
	Email         string
	Name          string
	PasswordHash  *string
	Source        string
	IsAdmin       bool
	Active        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LdapSourceID  *string
	LdapDn        *string
	Photo         []byte
	PhotoMime     *string
	TotpSecretEnc []byte
	TotpEnabled   bool
}

type UserGroup struct {
	UserID  string
	GroupID string
}
