// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO access_tokens (id, user_id, client_id, scopes, audience, refresh_token_id, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAccessTokenParams struct {
	ID             string
	UserID         string
	ClientID       string
	Scopes         string
	Audience       string
	RefreshTokenID *string
	ExpiresAt      time.Time
	CreatedAt      time.Time
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAccessToken,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.Audience,
		arg.RefreshTokenID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createAuthRequest = `-- name: CreateAuthRequest :exec
INSERT INTO auth_requests (id, request, created_at) VALUES ($1, $2, $3)
`

type CreateAuthRequestParams struct {
	ID        string
	Request   string
	CreatedAt time.Time
}

func (q *Queries) CreateAuthRequest(ctx context.Context, arg CreateAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, createAuthRequest, arg.ID, arg.Request, arg.CreatedAt)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, client_id, scopes, audience, amr, auth_time, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateRefreshTokenParams struct {
	ID        string
	UserID    string
	ClientID  string
	Scopes    string
	Audience  string
	Amr       string
	AuthTime  time.Time
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.Audience,
		arg.Amr,
		arg.AuthTime,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createSigningKey = `-- name: CreateSigningKey :exec
INSERT INTO signing_keys (id, alg, private_key_enc, public_key_der, active, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSigningKeyParams struct {
	ID            string
	Alg           string
	PrivateKeyEnc []byte
	PublicKeyDer  []byte
	Active        bool
	CreatedAt     time.Time
}

func (q *Queries) CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) error {
	_, err := q.db.ExecContext(ctx, createSigningKey,
		arg.ID,
		arg.Alg,
		arg.PrivateKeyEnc,
		arg.PublicKeyDer,
		arg.Active,
		arg.CreatedAt,
	)
	return err
}

const deleteAccessToken = `-- name: DeleteAccessToken :exec
DELETE FROM access_tokens WHERE id = $1
`

func (q *Queries) DeleteAccessToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAccessToken, id)
	return err
}

const deleteAccessTokensByRefreshToken = `-- name: DeleteAccessTokensByRefreshToken :exec
DELETE FROM access_tokens WHERE refresh_token_id = $1
`

func (q *Queries) DeleteAccessTokensByRefreshToken(ctx context.Context, refreshTokenID *string) error {
	_, err := q.db.ExecContext(ctx, deleteAccessTokensByRefreshToken, refreshTokenID)
	return err
}

const deleteAccessTokensByUserClient = `-- name: DeleteAccessTokensByUserClient :exec
DELETE FROM access_tokens WHERE user_id = $1 AND client_id = $2
`

type DeleteAccessTokensByUserClientParams struct {
	UserID   string
	ClientID string
}

func (q *Queries) DeleteAccessTokensByUserClient(ctx context.Context, arg DeleteAccessTokensByUserClientParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccessTokensByUserClient, arg.UserID, arg.ClientID)
	return err
}

const deleteAuthRequest = `-- name: DeleteAuthRequest :exec
DELETE FROM auth_requests WHERE id = $1
`

func (q *Queries) DeleteAuthRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthRequest, id)
	return err
}

const deleteExpiredAccessTokens = `-- name: DeleteExpiredAccessTokens :exec
DELETE FROM access_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredAccessTokens(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAccessTokens, expiresAt)
	return err
}

const deleteExpiredAuthRequests = `-- name: DeleteExpiredAuthRequests :exec
DELETE FROM auth_requests WHERE created_at < $1
`

func (q *Queries) DeleteExpiredAuthRequests(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthRequests, createdAt)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokens, expiresAt)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE id = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, id)
	return err
}

const deleteRefreshTokensByUserClient = `-- name: DeleteRefreshTokensByUserClient :exec
DELETE FROM refresh_tokens WHERE user_id = $1 AND client_id = $2
`

type DeleteRefreshTokensByUserClientParams struct {
	UserID   string
	ClientID string
}

func (q *Queries) DeleteRefreshTokensByUserClient(ctx context.Context, arg DeleteRefreshTokensByUserClientParams) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByUserClient, arg.UserID, arg.ClientID)
	return err
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT id, user_id, client_id, scopes, audience, refresh_token_id, expires_at, created_at FROM access_tokens WHERE id = $1
`

func (q *Queries) GetAccessToken(ctx context.Context, id string) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, getAccessToken, id)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.Audience,
		&i.RefreshTokenID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSigningKeys = `-- name: GetActiveSigningKeys :many
SELECT id, alg, private_key_enc, public_key_der, active, created_at FROM signing_keys WHERE active = TRUE ORDER BY created_at DESC
`

func (q *Queries) GetActiveSigningKeys(ctx context.Context) ([]SigningKey, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningKey
	for rows.Next() {
		var i SigningKey
		if err := rows.Scan(
			&i.ID,
			&i.Alg,
			&i.PrivateKeyEnc,
			&i.PublicKeyDer,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthRequestByCode = `-- name: GetAuthRequestByCode :one
SELECT id, code, request, created_at FROM auth_requests WHERE code = $1
`

func (q *Queries) GetAuthRequestByCode(ctx context.Context, code *string) (AuthRequest, error) {
	row := q.db.QueryRowContext(ctx, getAuthRequestByCode, code)
	var i AuthRequest
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Request,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthRequestByID = `-- name: GetAuthRequestByID :one
SELECT id, code, request, created_at FROM auth_requests WHERE id = $1
`

func (q *Queries) GetAuthRequestByID(ctx context.Context, id string) (AuthRequest, error) {
	row := q.db.QueryRowContext(ctx, getAuthRequestByID, id)
	var i AuthRequest
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Request,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, client_id, scopes, audience, amr, auth_time, expires_at, created_at FROM refresh_tokens WHERE id = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, id string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.Audience,
		&i.Amr,
		&i.AuthTime,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const setAuthRequestCode = `-- name: SetAuthRequestCode :exec
UPDATE auth_requests SET code = $1 WHERE id = $2
`

type SetAuthRequestCodeParams struct {
	Code *string
	ID   string
}

func (q *Queries) SetAuthRequestCode(ctx context.Context, arg SetAuthRequestCodeParams) error {
	_, err := q.db.ExecContext(ctx, setAuthRequestCode, arg.Code, arg.ID)
	return err
}

const updateAuthRequest = `-- name: UpdateAuthRequest :exec
UPDATE auth_requests SET request = $1 WHERE id = $2
`

type UpdateAuthRequestParams struct {
	Request string
	ID      string
}

func (q *Queries) UpdateAuthRequest(ctx context.Context, arg UpdateAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthRequest, arg.Request, arg.ID)
	return err
}
