// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package sqlcgen

import (
	"context"
)

const addAppPolicy = `-- name: AddAppPolicy :exec
INSERT INTO app_policies (application_id, group_id) VALUES ($1, $2)
`

type AddAppPolicyParams struct {
	ApplicationID string
	GroupID       string
}

func (q *Queries) AddAppPolicy(ctx context.Context, arg AddAppPolicyParams) error {
	_, err := q.db.ExecContext(ctx, addAppPolicy, arg.ApplicationID, arg.GroupID)
	return err
}

const countMatchingAppPolicies = `-- name: CountMatchingAppPolicies :one
SELECT COUNT(*)
FROM app_policies p
JOIN user_groups ug ON ug.group_id = p.group_id
WHERE p.application_id = $1 AND ug.user_id = $2
`

type CountMatchingAppPoliciesParams struct {
	ApplicationID string
	UserID        string
}

func (q *Queries) CountMatchingAppPolicies(ctx context.Context, arg CountMatchingAppPoliciesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMatchingAppPolicies, arg.ApplicationID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAppPolicies = `-- name: DeleteAppPolicies :exec
DELETE FROM app_policies WHERE application_id = $1
`

func (q *Queries) DeleteAppPolicies(ctx context.Context, applicationID string) error {
	_, err := q.db.ExecContext(ctx, deleteAppPolicies, applicationID)
	return err
}

const listAppPolicyGroupIDs = `-- name: ListAppPolicyGroupIDs :many
SELECT group_id FROM app_policies WHERE application_id = $1
`

func (q *Queries) ListAppPolicyGroupIDs(ctx context.Context, applicationID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAppPolicyGroupIDs, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_id string
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppPolicyGroupNames = `-- name: ListAppPolicyGroupNames :many
SELECT p.application_id, g.name
FROM app_policies p
JOIN groups g ON g.id = p.group_id
ORDER BY g.name
`

type ListAppPolicyGroupNamesRow struct {
	ApplicationID string
	Name          string
}

func (q *Queries) ListAppPolicyGroupNames(ctx context.Context) ([]ListAppPolicyGroupNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppPolicyGroupNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppPolicyGroupNamesRow
	for rows.Next() {
		var i ListAppPolicyGroupNamesRow
		if err := rows.Scan(&i.ApplicationID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByPolicyGroup = `-- name: ListApplicationsByPolicyGroup :many
SELECT a.id, a.name, a.slug,
       (SELECT COUNT(*) FROM app_policies p2 WHERE p2.application_id = a.id) AS group_count
FROM applications a
JOIN app_policies p ON p.application_id = a.id
WHERE p.group_id = $1
ORDER BY a.name
`

type ListApplicationsByPolicyGroupRow struct {
	ID         string
	Name       string
	Slug       string
	GroupCount int64
}

// Applications restricted to the group, with how many groups each one is
// bound to in total (1 means the group is its only way in).
func (q *Queries) ListApplicationsByPolicyGroup(ctx context.Context, groupID string) ([]ListApplicationsByPolicyGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationsByPolicyGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsByPolicyGroupRow
	for rows.Next() {
		var i ListApplicationsByPolicyGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.GroupCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, created_at, source, ldap_source_id, grants_admin, upstream_source_id FROM groups ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Source,
			&i.LdapSourceID,
			&i.GrantsAdmin,
			&i.UpstreamSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLaunchableApplications = `-- name: ListLaunchableApplications :many
SELECT DISTINCT a.id, a.name, a.slug, a.launch_url, a.created_at, a.updated_at, a.kind, a.description, a.icon, a.icon_mime, a.proxy_hosts, a.restricted
FROM applications a
LEFT JOIN app_policies p ON p.application_id = a.id
WHERE a.launch_url != ''
  AND (NOT a.restricted
       OR p.group_id IN (SELECT group_id FROM user_groups WHERE user_id = $1))
ORDER BY a.name
`

func (q *Queries) ListLaunchableApplications(ctx context.Context, userID string) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listLaunchableApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LaunchUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.Description,
			&i.Icon,
			&i.IconMime,
			&i.ProxyHosts,
			&i.Restricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationRestricted = `-- name: SetApplicationRestricted :exec
UPDATE applications SET restricted = $1 WHERE id = $2
`

type SetApplicationRestrictedParams struct {
	Restricted bool
	ID         string
}

func (q *Queries) SetApplicationRestricted(ctx context.Context, arg SetApplicationRestrictedParams) error {
	_, err := q.db.ExecContext(ctx, setApplicationRestricted, arg.Restricted, arg.ID)
	return err
}
