// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package sqlcgen

import (
	"context"
)

const addAppPolicy = `-- name: AddAppPolicy :exec
INSERT INTO app_policies (application_id, group_id) VALUES ($1, $2)
`

type AddAppPolicyParams struct {
	ApplicationID string
	GroupID       string
}

func (q *Queries) AddAppPolicy(ctx context.Context, arg AddAppPolicyParams) error {
	_, err := q.db.ExecContext(ctx, addAppPolicy, arg.ApplicationID, arg.GroupID)
	return err
}

const countAppPolicies = `-- name: CountAppPolicies :one
SELECT COUNT(*) FROM app_policies WHERE application_id = $1
`

func (q *Queries) CountAppPolicies(ctx context.Context, applicationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppPolicies, applicationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMatchingAppPolicies = `-- name: CountMatchingAppPolicies :one
SELECT COUNT(*)
FROM app_policies p
JOIN user_groups ug ON ug.group_id = p.group_id
WHERE p.application_id = $1 AND ug.user_id = $2
`

type CountMatchingAppPoliciesParams struct {
	ApplicationID string
	UserID        string
}

func (q *Queries) CountMatchingAppPolicies(ctx context.Context, arg CountMatchingAppPoliciesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMatchingAppPolicies, arg.ApplicationID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAppPolicies = `-- name: DeleteAppPolicies :exec
DELETE FROM app_policies WHERE application_id = $1
`

func (q *Queries) DeleteAppPolicies(ctx context.Context, applicationID string) error {
	_, err := q.db.ExecContext(ctx, deleteAppPolicies, applicationID)
	return err
}

const listAppPolicyGroupIDs = `-- name: ListAppPolicyGroupIDs :many
SELECT group_id FROM app_policies WHERE application_id = $1
`

func (q *Queries) ListAppPolicyGroupIDs(ctx context.Context, applicationID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAppPolicyGroupIDs, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_id string
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, created_at, source, ldap_source_id FROM groups ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Source,
			&i.LdapSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLaunchableApplications = `-- name: ListLaunchableApplications :many
SELECT DISTINCT a.id, a.name, a.slug, a.launch_url, a.created_at, a.updated_at
FROM applications a
LEFT JOIN app_policies p ON p.application_id = a.id
WHERE a.launch_url != ''
  AND (p.application_id IS NULL
       OR p.group_id IN (SELECT group_id FROM user_groups WHERE user_id = $1))
ORDER BY a.name
`

func (q *Queries) ListLaunchableApplications(ctx context.Context, userID string) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listLaunchableApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LaunchUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
