// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: smtp.sql

package sqlcgen

import (
	"context"
	"time"
)

const getSMTPSettings = `-- name: GetSMTPSettings :one
SELECT id, enabled, host, port, username, password_enc, from_address, from_name, encryption, updated_at FROM smtp_settings WHERE id = 1
`

func (q *Queries) GetSMTPSettings(ctx context.Context) (SmtpSetting, error) {
	row := q.db.QueryRowContext(ctx, getSMTPSettings)
	var i SmtpSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.FromAddress,
		&i.FromName,
		&i.Encryption,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSMTPPassword = `-- name: UpdateSMTPPassword :exec
UPDATE smtp_settings SET password_enc = $1, updated_at = $2 WHERE id = 1
`

type UpdateSMTPPasswordParams struct {
	PasswordEnc []byte
	UpdatedAt   time.Time
}

func (q *Queries) UpdateSMTPPassword(ctx context.Context, arg UpdateSMTPPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateSMTPPassword, arg.PasswordEnc, arg.UpdatedAt)
	return err
}

const updateSMTPSettings = `-- name: UpdateSMTPSettings :exec
UPDATE smtp_settings
SET enabled = $1, host = $2, port = $3, username = $4,
    from_address = $5, from_name = $6, encryption = $7, updated_at = $8
WHERE id = 1
`

type UpdateSMTPSettingsParams struct {
	Enabled     bool
	Host        string
	Port        int32
	Username    string
	FromAddress string
	FromName    string
	Encryption  string
	UpdatedAt   time.Time
}

func (q *Queries) UpdateSMTPSettings(ctx context.Context, arg UpdateSMTPSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSMTPSettings,
		arg.Enabled,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.FromAddress,
		arg.FromName,
		arg.Encryption,
		arg.UpdatedAt,
	)
	return err
}
