// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, name, password_hash, source, ldap_source_id, ldap_dn, is_admin, active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, username, email, name, password_hash, source, is_admin, active, created_at, updated_at, ldap_source_id, ldap_dn, photo, photo_mime, totp_secret_enc, totp_enabled
`

type CreateUserParams struct {
	ID           string
	Username     string
	Email        string
	Name         string
	PasswordHash *string
	Source       string
	LdapSourceID *string
	LdapDn       *string
	IsAdmin      bool
	Active       bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Source,
		arg.LdapSourceID,
		arg.LdapDn,
		arg.IsAdmin,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Source,
		&i.IsAdmin,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LdapSourceID,
		&i.LdapDn,
		&i.Photo,
		&i.PhotoMime,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, name, password_hash, source, is_admin, active, created_at, updated_at, ldap_source_id, ldap_dn, photo, photo_mime, totp_secret_enc, totp_enabled FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Source,
		&i.IsAdmin,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LdapSourceID,
		&i.LdapDn,
		&i.Photo,
		&i.PhotoMime,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, name, password_hash, source, is_admin, active, created_at, updated_at, ldap_source_id, ldap_dn, photo, photo_mime, totp_secret_enc, totp_enabled FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Source,
		&i.IsAdmin,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LdapSourceID,
		&i.LdapDn,
		&i.Photo,
		&i.PhotoMime,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, name, password_hash, source, is_admin, active, created_at, updated_at, ldap_source_id, ldap_dn, photo, photo_mime, totp_secret_enc, totp_enabled FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Source,
		&i.IsAdmin,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LdapSourceID,
		&i.LdapDn,
		&i.Photo,
		&i.PhotoMime,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
	)
	return i, err
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.created_at, g.source, g.ldap_source_id, g.grants_admin
FROM groups g
JOIN user_groups ug ON ug.group_id = g.id
WHERE ug.user_id = $1
ORDER BY g.name
`

func (q *Queries) ListUserGroups(ctx context.Context, userID string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Source,
			&i.LdapSourceID,
			&i.GrantsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1, updated_at = $2 WHERE id = $3
`

type UpdateUserPasswordParams struct {
	PasswordHash *string
	UpdatedAt    time.Time
	ID           string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}
