// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const countWebauthnCredentials = `-- name: CountWebauthnCredentials :one
SELECT COUNT(*) FROM webauthn_credentials WHERE user_id = $1
`

func (q *Queries) CountWebauthnCredentials(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebauthnCredentials, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebauthnCredential = `-- name: CreateWebauthnCredential :exec
INSERT INTO webauthn_credentials (id, user_id, credential_id, name, data, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWebauthnCredentialParams struct {
	ID           string
	UserID       string
	CredentialID string
	Name         string
	Data         string
	CreatedAt    time.Time
}

func (q *Queries) CreateWebauthnCredential(ctx context.Context, arg CreateWebauthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createWebauthnCredential,
		arg.ID,
		arg.UserID,
		arg.CredentialID,
		arg.Name,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const deleteWebauthnCredential = `-- name: DeleteWebauthnCredential :exec
DELETE FROM webauthn_credentials WHERE id = $1 AND user_id = $2
`

type DeleteWebauthnCredentialParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteWebauthnCredential(ctx context.Context, arg DeleteWebauthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebauthnCredential, arg.ID, arg.UserID)
	return err
}

const listWebauthnCredentials = `-- name: ListWebauthnCredentials :many
SELECT id, user_id, credential_id, name, data, created_at, last_used_at FROM webauthn_credentials WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListWebauthnCredentials(ctx context.Context, userID string) ([]WebauthnCredential, error) {
	rows, err := q.db.QueryContext(ctx, listWebauthnCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.Name,
			&i.Data,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebauthnCredential = `-- name: UpdateWebauthnCredential :exec
UPDATE webauthn_credentials SET data = $1, last_used_at = $2 WHERE credential_id = $3
`

type UpdateWebauthnCredentialParams struct {
	Data         string
	LastUsedAt   sql.NullTime
	CredentialID string
}

func (q *Queries) UpdateWebauthnCredential(ctx context.Context, arg UpdateWebauthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateWebauthnCredential, arg.Data, arg.LastUsedAt, arg.CredentialID)
	return err
}
